### ISSUE TITLE
Scaffolding command for new app fails due to lock file error

### ISSUE THREAD

**Issue by jost-s** [holochain-open-dev/templates#8]
When I execute the command to scaffold a new app under macOS, I get the following error:

```sh
$ nix run github:holochain-open-dev/templates#hc-scaffold-app-template -- web-app
do you want to allow configuration setting 'extra-substituters' to be set to 'https://holochain-open-dev.cachix.org' (y/N)? y
do you want to permanently mark this value as trusted (y/N)? y
do you want to allow configuration setting 'extra-trusted-public-keys' to be set to 'holochain-open-dev.cachix.org-1:3Tr+9in6uo44Ga7qiuRIfOTFXog+2+YbyhwI/Z6Cp4U=' (y/N)? y
do you want to permanently mark this value as trusted (y/N)? y
error:
       … while updating the lock file of flake 'github:holochain-open-dev/templates/aefe91aa3fae296e5c7e685fc413696f0adfb46c'

       error: cannot write modified lock file of flake 'github:holochain-open-dev/templates' (use '--no-write-lock-file' to ignore)
```

Executing the same command with the suggested option succeeds
```sh
$ nix run github:holochain-open-dev/templates#hc-scaffold-app-template --no-write-lock-file -- web-app
```

**Comment by guillemcordoba** [comment]
This should be fixed now, could you try it out again?

**Comment by jost-s** [comment]
It still shows the same error for me when running the above command.

**Comment by guillemcordoba** [comment]
Hum can you try it with refresh? Maybe it's still cached?

```bash
nix run github:holochain-open-dev/templates#hc-scaffold-app-template --refresh -- web-app
```

I did try it on a MacOS and it worked...

**Comment by jost-s** [comment]
I don't know what's happening, but I get the same
```sh
$ nix run github:holochain-open-dev/templates#hc-scaffold-app-template --refresh -- web-app
error:
       … while updating the lock file of flake 'github:holochain-open-dev/templates/e443646c27ceee63e383e856aba73409c1879b74'

       error: cannot write modified lock file of flake 'github:holochain-open-dev/templates' (use '--no-write-lock-file' to ignore)
```

**Comment by guillemcordoba** [comment]
Really interesting... What's your nix version? [Maybe this is a bug in nix](https://github.com/NixOS/nix/issues/6050#issuecomment-1709393833)?

**Comment by jost-s** [comment]
I have nix 2.18.2
